version: '3.7'

services:
  vue:
    build:
      context: ./myga_front
      dockerfile: dockerfile-vue
    ports:
      - "5173:5173"
    volumes:
      - vue_build:/dist
    command: ["npm", "run", "dev"]

  spring:
    build:
      context: ./myga_back
      dockerfile: dockerfile-spring
    ports:
      - "8037:8037"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - spring

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"

volumes:
  vue_build:
