version: '3.7'

services:
  vue:
    build:
      context: ./myga_front
      dockerfile: dockerfile-vue
    ports:
      - "5173:5173"
    volumes:
      - vue_build:/dist
    command: ["npm", "run", "dev", "--", "--host"]

  spring:
    build:
      context: ./myga_back
      dockerfile: dockerfile-spring
    ports:
      - "8037:8037"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/myga/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/myga/nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/certbot/www:/var/www/certbot
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"
 
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins:/var/jenkins_home
      - /home:/home
    ports:
      - 8080:8080
    privileged: true
    user: root
    environment:
      - TZ=Asia/Seoul

volumes:
  vue_build:
