version: '3.7'

services:
  vue-app:
    build:
      context: ./myga_front
      dockerfile: dockerfile-vue
    volumes:
      - vue_build:/dist
    command: ["sh", "-c", "npm install && npm run build && cp -r /app/dist /dist"]

volumes:
  vue_build: