server:
  port: 8037

# 기본 설정
spring:
  profiles:
    active: prod

# 개발 환경 설정
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dev_db
    username: dev_user
    password: dev_password

# 프로덕션 환경 설정
---
spring:
  config:
    activate:
      on-profile: prod
  datasource.master:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MASTER_DB_HOST}:${MASTER_DB_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  datasource.slave:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SLAVE_DB_HOST}:${SLAVE_DB_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true