spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${MYSQL_DATASOURCE_URL}
#    username: ${MYSQL_DATASOURCE_USERNAME}
#    password: ${MYSQL_DATASOURCE_PASSWORD}

#    jpa:
#      hibernate:
#        ddl-auto: create
#      show-sql: false
#      database: mysql
#      database-platform: org.hibernate.dialect.MySQL8Dialect
#      properties:
#        hibernate:
#          format_sql: true